### ISSUE TITLE
Master build - version numbers

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Testing#16]
Looking at the latest build of master - why would it be producing beta version numbers? 

https://ci.appveyor.com/project/GitTools/gittools-testing/branch/master

**Comment by dazinator** [comment]
Oh gees.. I missed this: https://github.com/GitTools/GitTools.Testing/blob/master/GitVersionConfig.yaml#L4

**Comment by dazinator** [comment]
Should we change that so that master produces stable numbers? The only model I am really used to working with is git flow - so having master produce beta packages has thrown me.. What's the reasoning behind this - how do we produce new stable versions with this in place?

**Comment by asbjornu** [comment]
I see no reason having this in place, seeing how stable builds of dependent libraries like GitVersion exist. This library has been proven stable enough to remove that `beta` tag, imo.
